frase = str(input('Colque a frase: '))
ases = frase.lower().count('a')
dividido = frase.split()
chares = len(frase)
print('Numero de "a" na frase: {}'.format(ases))
print(frase.lower().find('a'))
contra = dividido[-1][::-1].find('a')
print(chares)
print((chares - 1) - contra)